# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_lltm_forward <- function(input, weights, bias, old_h, old_cell) {
    .Call('_lltm_rcpp_lltm_forward', PACKAGE = 'lltm', input, weights, bias, old_h, old_cell)
}

rcpp_lltm_backward <- function(grad_h, grad_cell, new_cell, input_gate, output_gate, candidate_cell, X, gate_weights, weights) {
    .Call('_lltm_rcpp_lltm_backward', PACKAGE = 'lltm', grad_h, grad_cell, new_cell, input_gate, output_gate, candidate_cell, X, gate_weights, weights)
}

lltm_raise_exception <- function() {
    invisible(.Call('_lltm_lltm_raise_exception', PACKAGE = 'lltm'))
}

